export const serbiaLocations = [
  // =========================
  // Cities (29)
  // =========================
  "Beograd",
  "Novi Sad",
  "Niš",
  "Kragujevac",
  "Subotica",
  "Zrenjanin",
  "Pančevo",
  "Čačak",
  "Kraljevo",
  "Novi Pazar",
  "Smederevo",
  "Leskovac",
  "Užice",
  "Vranje",
  "Valjevo",
  "Šabac",
  "Požarevac",
  "Sombor",
  "Pirot",
  "Kikinda",
  "Jagodina",
  "Zaječar",
  "Bor",
  "Prokuplje",
  "Loznica",
  "Sremska Mitrovica",
  "Vršac",
  "Paraćin",
  "Aleksinac",

  // =========================
  // Municipalities (145 + 17 Belgrade municipalities)
  // =========================
  // Belgrade Municipalities
  "Voždovac",
  "Vračar",
  "Zvezdara",
  "Zemun",
  "Novi Beograd",
  "Palilula",
  "Rakovica",
  "Savski venac",
  "Stari grad",
  "Čukarica",
  "Surčin",
  "Barajevo",
  "Grocka",
  "Lazarevac",
  "Mladenovac",
  "Obrenovac",
  "Sopot",

  // Rest Municipalities
  "Ada",
  "Aleksandrovac",
  "Aleksinac",
  "Alibunar",
  "Apatin",
  "Aranđelovac",
  "Arilje",
  "Babušnica",
  "Bajina Bašta",
  "Batočina",
  "Bač",
  "Bačka Palanka",
  "Bačka Topola",
  "Bački Petrovac",
  "Bela Crkva",
  "Bela Palanka",
  "Beočin",
  "Blace",
  "Bogatić",
  "Bojnik",
  "Boljevac",
  "Bosilegrad",
  "Brus",
  "Bujanovac",
  "Valjevo",
  "Varvarin",
  "Velika Plana",
  "Vladimirci",
  "Vladičin Han",
  "Vlasotince",
  "Vršac",
  "Vučitrn",
  "Gadžin Han",
  "Glogovac",
  "Golubac",
  "Gora",
  "Gornji Milanovac",
  "Despotovac",
  "Dimitrovgrad",
  "Doljevac",
  "Žabalj",
  "Žabari",
  "Žagubica",
  "Žitište",
  "Žitorađa",
  "Zaječar",
  "Zvezdara",
  "Zubin Potok",
  "Zvečan",
  "Ivanjica",
  "Inđija",
  "Irig",
  "Jagodina",
  "Kanjiža",
  "Kladovo",
  "Knić",
  "Knjaževac",
  "Kosjerić",
  "Kovačica",
  "Kovin",
  "Kosovo Polje",
  "Kosovska Mitrovica",
  "Krupanj",
  "Kruševac",
  "Kula",
  "Kuršumlija",
  "Kučevo",
  "Lajkovac",
  "Lapovo",
  "Lebane",
  "Leskovac",
  "Ljig",
  "Ljubovija",
  "Lučani",
  "Majdanpek",
  "Mali Iđoš",
  "Mali Zvornik",
  "Medveđa",
  "Merošina",
  "Mionica",
  "Negotin",
  "Niš",
  "Nova Crnja",
  "Nova Varoš",
  "Novi Bečej",
  "Novi Kneževac",
  "Novi Pazar",
  "Novi Sad",
  "Odžaci",
  "Opovo",
  "Osečina",
  "Petrovac na Mlavi",
  "Pećinci",
  "Plandište",
  "Pirot",
  "Pirot opština",
  "Požarevac",
  "Požega",
  "Preševo",
  "Priboj",
  "Prijepolje",
  "Prokuplje",
  "Rača",
  "Raška",
  "Rekovac",
  "Ruma",
  "Senta",
  "Sečanj",
  "Sjenica",
  "Smederevo",
  "Smederevska Palanka",
  "Sokobanja",
  "Srbobran",
  "Sremska Mitrovica",
  "Sremski Karlovci",
  "Stara Pazova",
  "Subotica",
  "Svrljig",
  "Temerin",
  "Titel",
  "Topola",
  "Trgovište",
  "Trstenik",
  "Tutin",
  "Ćićevac",
  "Ćuprija",
  "Ub",
  "Užice",
  "Uroševac",
  "Futog",
  "Han Pijesak",
  "Crna Trava",
  "Čajetina",
  "Čoka",
  "Šabac",
  "Šid",
  "Štavalj",

  // =========================
  // Towns / Large settlements (5000+ population)
  // =========================
  "Stepojevac",
  "Kaluđerica",
  "Borča",
  "Ovča",
  "Resnik",
  "Velika Moštanica",
  "Barič",
  "Umčari",
  "Ripanj",
  "Krnjača",
  "Padinska Skela",
  "Vinča",
  "Leštane",
  "Ritopek",
  "Sremčica",
  "Petlovo Brdo",
  "Banovo Brdo",
  "Mali Mokri Lug",
  "Veliki Mokri Lug",
  "Altina",
  "Ledine",
  "Batajnica",
  "Ugrinovci",
  "Zuce",
  "Šopić",
  "Dudovica",
  "Divci",
  "Popučke",
  "Petnica",
  "Jazovik",
  "Bela Crkva (Valjevo)",
  "Brankovina",
  "Kosančić",
  "Gračac",
  "Medoševac",
  "Donja Trnava",
  "Čokot",
  "Pasi Poljana",
  "Malča",
  "Velika Plana (Leskovac)",
  "Brestovac",
  "Pečenjevce",
  "Grdelica",
  "Lebane",
  "Bošnjace",
  "Badovinci",
  "Klenje",
  "Mačvanski Prnjavor",
  "Pribojska Banja",
  "Ljubovija",
  "Tršić",
  "Lipolist",
  "Debrc",
  "Prhovo",
  "Kupinovo",
  "Pećinci",
  "Kovinac",
  "Banatsko Novo Selo",
  "Kačarevo",
  "Starčevo",
  "Ivanovo",
  "Omoljica",
  "Glogonj",
  "Crepaja",
  "Sefkerin",
  "Kovačica",
  "Debeljača",
  "Padina",
  "Bački Jarak",
  "Veternik",
  "Kisač",
  "Rumenka",
  "Kać",
  "Futog",
  "Petrovaradin",
  "Sremska Kamenica",
  "Bečej",
  "Bačka Topola",
  "Mali Iđoš",
  "Kanjiža",
  "Senta",
  "Čoka",
  "Ada",
  "Mol",
  "Torda",
  "Banatsko Karađorđevo",
];
